### ISSUE TITLE
Add a Sample for Other Xenforo-based Sites (e.g. AlternateHistory.com)

### ISSUE THREAD

**Issue by deepbhattacharya** [kemayo/leech#18]
Could you please add a sample/example for AH.com?

**Comment by kemayo** [comment]
Basically, AH.com will now work. I haven't given a generic example of how to do it via the JSON config, though it wouldn't be _too_ hard, only because it's simpler to add to the registered xenforo sites like I did in that commit.

**Comment by deepbhattacharya** [comment]
Is it possible to download full threads? I ask because it's hard to do that in other ways (for example fanficfare forbids it for fear people will misuse it). There are story-only threads in AH that have no threadmarks and can only be downloaded in bulk.

**Comment by kemayo** [comment]
I've just added something which will make it workable in 929284b67dc06d4c0d646a7f42ad15281c2e28ae, at least if you're willing to fiddle with JSON. See [examples/dungeonkeeperami.json](https://github.com/kemayo/leech/blob/master/examples/dungeonkeeperami.json) for an example of grabbing everything from a xenforo story-only thread.

**Comment by deepbhattacharya** [comment]
I'm getting 403 error when it tries to access page 2 of a thread. When I try an arbitrary site with page 1 only (removing the next page selector) the epub gets created with page 1 content. (Missing images but I presume I'm missing some configuration.)

I was expecting this to work (file saved in example folder, reluctant-fuhrer.json):

`{

    "url": "https://www.alternatehistory.com/forum/threads/an-extremely-reluctant-fuhrer-story-only-thread.388640/",

    "title": "An Extremely Reluctant Fuhrer",

    "author": "johnboy",

    "content_selector": "li.message article blockquote.messageText",

    "filter_selector": ".sharedaddy, .wpcnt, style",

    "next_selector": "link[rel=next]"

}`

I have the logins saved in leech.json:

`{
    "logins": {
        "AlternateHistory": ["****", "******"]
    }
}`

The error I get when trying to download the thread:

(leech-MifW-BsE) C:\Users\Deep\Software\leech>python leech.py examples\reluctantfuhrer.json
[sites] Handler: <class 'sites.arbitrary.Arbitrary'> (examples\reluctantfuhrer.json)
[sites.arbitrary] Extracting chapter @ https://www.alternatehistory.com/forum/threads/an-extremely-reluctant-fuhrer-story-only-thread.388640/
[sites.arbitrary] Extracting chapter @ https://www.alternatehistory.com/forum/threads/an-extremely-reluctant-fuhrer-story-only-thread.388640/page-2
[sites] Load failed: waiting 10 to retry (<Response [403]>)
[sites] Load failed: waiting 10 to retry (<Response [403]>)
[sites] Load failed: waiting 10 to retry (<Response [403]>)
Traceback (most recent call last):
  File "leech.py", line 157, in <module>
    cli()
  File "C:\Users\Deep\.virtualenvs\leech-MifW-BsE\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Deep\.virtualenvs\leech-MifW-BsE\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Deep\.virtualenvs\leech-MifW-BsE\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Deep\.virtualenvs\leech-MifW-BsE\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Deep\.virtualenvs\leech-MifW-BsE\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "leech.py", line 150, in download
    story = open_story(site, url, session, login, options)
  File "leech.py", line 101, in open_story
    story = handler.extract(url)
  File "C:\Users\Deep\Software\leech\sites\arbitrary.py", line 80, in extract
    for chapter in self._chapter(content_url, definition):
  File "C:\Users\Deep\Software\leech\sites\arbitrary.py", line 100, in _chapter
    soup = self._soup(url)
  File "C:\Users\Deep\Software\leech\sites\__init__.py", line 138, in _soup
    return self._soup(url, method=method, retry=retry - 1, retry_delay=retry_delay, **kw)
  File "C:\Users\Deep\Software\leech\sites\__init__.py", line 138, in _soup
    return self._soup(url, method=method, retry=retry - 1, retry_delay=retry_delay, **kw)
  File "C:\Users\Deep\Software\leech\sites\__init__.py", line 138, in _soup
    return self._soup(url, method=method, retry=retry - 1, retry_delay=retry_delay, **kw)
  File "C:\Users\Deep\Software\leech\sites\__init__.py", line 139, in _soup
    raise SiteException("Couldn't fetch", url)
sites.SiteException: ("Couldn't fetch", 'https://www.alternatehistory.com/forum/threads/an-extremely-reluctant-fuhrer-story-only-thread.388640/page-2')

**Comment by kemayo** [comment]
Hm, okay. That's because the login stuff only works when you're doing this through a known site, rather than the JSON definitions. I can probably add a more comprehensive full-thread option that's actually part of the XenForo site definition, and that'll solve everything.
