### ISSUE TITLE
Issue when downloading from fiction.live

### ISSUE THREAD

**Issue by hdloader11** [kemayo/leech#30]
I was trying to download the below quest : 

https://fiction.live/stories/Star-Wars-Twilight-of-the-Republic/zZMpSXnx8f7RxJnoa

And I've gotten this error : 

   return callback(*args, **kwargs)
  File "leech.py", line 152, in download
    story = open_story(site, url, session, login, options)
  File "leech.py", line 103, in open_story
    story = handler.extract(url)
  File "C:\Users\kerem\Desktop\leech-master\sites\fictionlive.py", line 67, in extract
    if int(choice) < len(segment['choices']):
ValueError: invalid literal for int() with base 10: 'o'

**Comment by kemayo** [comment]
Man, the API of this site makes weird choices. `choice` there is normally (as in, everywhere else) an index in the votes array... but in this one place it's a string `'onbashira :V'`. 🤷‍♂
