### ISSUE TITLE
Use flexible dependencies

### ISSUE THREAD

**Issue by flying-sheep** [kemayo/leech#38]
The old versions of binary dependencies being specified don't provide wheels while newer versions do and work fine.

Any reason you specify specific versions instead of semantic version bounds?

**Comment by kemayo** [comment]
The `requirements.txt` there is just literally the output of `pip freeze`. I've never really bothered to fiddle with it, beyond updating when needed.

**Comment by kemayo** [comment]
#39 to switch to poetry will, coincidentally because of default behavior, be less-fixed.

**Comment by flying-sheep** [comment]
OK, great! typed-ast seems to have vanished completely …

**Comment by kemayo** [comment]
Yeah, the pip requirements.txt style does kinda merge together the actual-dependencies and their sub-dependencies in an easy-to-confuse manner, resulting in things like that lingering around.

**Comment by flying-sheep** [comment]
Well, I used to use requirements.txt as declarative dependencies and not as a lockfile, but that discussion is moot now anyway. Good choice, poetry rocks!
