### ISSUE TITLE
Unexpected Keyword argument 'chapter_order'

### ISSUE THREAD

**Issue by mrothbart** [kemayo/leech#40]
I am using the most updated version (pulled today) with all dependencies installed so far as I know. Books like The Wandering Inn work fine, but iamgoingtodie.json fails with the chapter_order option causing an error. Taking out the option fails as well.

**Comment by kemayo** [comment]
Oops, it looks like I committed an example file which contained some syntax I was tinkering with but hadn't committed along with it. Thanks for letting me know -- I'm just going to delete that specific example.
