### ISSUE TITLE
Add support to royalroad with an example json?

### ISSUE THREAD

**Issue by mrothbart** [kemayo/leech#42]
Royalroad has the same format for all stories. Would it be possible to get a JSON example file for that site? This would solve issues like iamgoingtodie not working, along with several other stories.

**Comment by kemayo** [comment]
Royalroad has a custom handler, so it should just-work if you pass in the URL of the story.

e.g.:
> ./leech.py https://www.royalroad.com/fiction/21844/i-am-going-to-die-in-this-game-like-dimension
