### ISSUE TITLE
Fanfiction.net not working.

### ISSUE THREAD

**Issue by WiseThrush** [kemayo/leech#53]
I got this error when I tried python leech.py https://www.fanfiction.net/s/12044591/1/Forged-Destiny
> [sites] Load failed: waiting 10 to retry (403: https://www.fanfiction.net/s/12044591/)

It's working for fiction.live though.

**Comment by kemayo** [comment]
Yeah, fanfiction.net very recently did a migration to use CloudFlare that blocked most non-browser methods of loading their pages. The only way around it so far is to run a proxy server that (basically) runs a copy of Chrome that loads pages for you... which is a bit of a pain.

They've said that they're going to be launching an API that people can use to download things, so ideally they'll do that promptly and I can just switch to it.

**Comment by WiseThrush** [comment]
Alright, thanks for the info. And the program too, it's been quite helpful.

**Comment by kemayo** [comment]
Incidentally, because I had a copy sitting around from a while ago, [here's the story you were trying to get](https://filebin.net/qrawaxoihizf97u8/Forged_Destiny__RWBY___Gamer__-_Coeur_Al_Aran.epub?t=4d64y9br).
