### ISSUE TITLE
(invalid html) Stray ampersand in chapter title

### ISSUE THREAD

**Issue by ClaasJG** [kemayo/leech#56]
Hello,

I could not open the chapter [Interlude: Lost & Found](https://practicalguidetoevil.wordpress.com/2020/12/22/interlude-lost-found/) of 'A Practical Guide to Evil' Book 6 using a Toline Shine 3 (This is also reproducible using the chrome Extension [EPUBReader](https://chrome.google.com/webstore/detail/epubreader/jhhclmfgfllimlhabjkgkeebkbiadflb)) because, it contains invalid html.  I am using leech and the example json from d50f23d07b854d8dfd50a0a1de92bf051c275a1b .

The title of the chapter contains a '&' symbol. This 'stray ambiguous  ampersand' is the cause for the error and should be replaced with `&amp;`.
See the following html taken from the downloaded ePub:

```html
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
   <title>Interlude: Lost & Found</title>
   <link rel="stylesheet" type="text/css" href="../Styles/base.css" />
</head>
<body>
   <h1>Interlude: Lost & Found</h1>
   <div class="entry-content">
   <blockquote class="wp-block-quote">
   [...]
</body>
```

I tried to fix this by escaping the title using [html.escape](https://docs.python.org/3/library/html.html) 
at [ebook\_init_.py # chapter_html @ Line 93](https://github.com/kemayo/leech/blob/d50f23d07b854d8dfd50a0a1de92bf051c275a1b/ebook/__init__.py#L93).

```python
chapters.append((
    title,
    f'{story.id}/chapter{i + 1}.html',
    html_template.format(title=html.escape(title), text=contents)
))
```

I do not generally escape the chapter title, because otherwise it will be displayed as `Interlude: Lost &amp; Found` in the index.

This quick and dirty fix allows the Toline Shine 3 to display the chapter, Be aware, that a stray '&' withing the content would produces a similar error.

Thanks for leech and have a nice day

-ClaasJG

**Comment by kemayo** [comment]
Interesting, I'm kind of surprised that it's taken so long for this to turn up as an issue.

**Comment by ClaasJG** [comment]
Good evening,

thanks for the fix. I don't know if you expected me to close this issue or if you left it open as remainder that invalid content html is still a problem. I consider my problem fixed and this issue resolved and just assume I may close it.

Have a nice day

-ClaasJG

**Comment by kemayo** [comment]
Sure, go for it. I was leaving it open as a reminder to myself that I should make the template HTML more robust, but making a dedicated ticket for that would be a more-correct action. :D
