### ISSUE TITLE
Getting nameError with requests-cache 

### ISSUE THREAD

**Issue by lati111** [kemayo/leech#59]
I've been trying to get it working for a while now (still pretty new to python) but I keep getting the following error
![image](https://user-images.githubusercontent.com/75079614/111848444-55ad5300-890b-11eb-9d36-0b6dbeec4f68.png)
And no matter what I do I can't seem to be getting it working, it might be an issue on my end because I'm not all that good with this stuff but I feel like it's the code in this case?

Either way I'd appreciate a bit of help trying to get it fixed, if this kind of post doesn't belong here feel free to delete it, I could just not read the novel too
Thanks in advance!

**Comment by kemayo** [comment]
Not sure exactly how one winds up with it checked out in a .poetry directory like that, but the basic problem you're having is that the dependencies aren't installed. You can probably run `poetry install` and then `poetry run leech examples\practical1.json` and have it work.

**Comment by lati111** [comment]
Hmm I see, I'll go ahead and try to reinstall it with that method, I probably messed something up trying to install it, thanks for the help!

**Comment by lati111** [comment]
It works now, thank you so much!!!
