### ISSUE TITLE
Add a way to run this from a diffrent folder

### ISSUE THREAD

**Issue by KeinNiemand** [kemayo/leech#67]
Poetry makes it impossible to run things from a diffrent folder you have to cd into the folder, and then run it with potry. This makes it impossible to run leech from a diffrent folder and I don't want to run leech in the folder it's in becouse I want my final epubs somewhere else and I don't want to write to that folder in the script I'm using to download stuff with leech.
Edit Figured out a way to run it outside by using poetry build then installing the tar ball that produces with pip3 install but that build dosn't include nececary files so it dosn't really work (fixed it will probably open a diffrent issue and a pull request to fix it). Will leave this open for now since there should at least be some instuction somewhere on how to build and install this so you can run it outside.

**Comment by kemayo** [comment]
That commit is sort of tangential -- it provides a way to run it still from the same folder, but setting the output to go somewhere else via e.g. `--output-dir /tmp`.

**Comment by ClaasJG** [comment]
You can use [poetry run](https://python-poetry.org/docs/cli/#run) i.e. `poetry run bash -c 'cd ./outputfolder && python3 ../leech/leech.py ${url}'` to run from a different folder. But I guess its a bit clumsy and `--output-dir` is the better way.
