### ISSUE TITLE
Python 3.6 no longer supported

### ISSUE THREAD

**Issue by KeinNiemand** [kemayo/leech#70]
I tried running leech with Python 3.6 but got the following error: "TypeError: namedtuple() got an unexpected keyword argument 'defaults'" this is caused by somthing not beeing supported by python 3.6 and needing at least python 3.7, I suggest updating the readme to say that python 3.7 is required.

**Comment by kemayo** [comment]
Good point, thank you. I actually thought I had already done that, but it looks like I forgot!
