### ISSUE TITLE
Add options to leave spoilers in the chapter instead of moving them

### ISSUE THREAD

**Issue by KeinNiemand** [kemayo/leech#75]
Leech gives you the option to include or not include content in spoiler tags but if they are  included they are moved to a footnote at the end of the file. Some story have important information in spoiler tags so fliping back and forth to that footnote page is anyoing.
While I use a modified version of the program that just comments out the clean spoilers line a better solution would be to add an option to do this.

**Comment by kemayo** [comment]
The current experience works out okay for me because on a Kindle the footnotes are set up to trigger footnote-popups so I don't need to jump around.

That said, an option to "clean" them by leaving them inline seems reasonable -- do you think they need some sort of markup added to indicate which bits of the content were previously hidden-as-spoilers, or would just unwrapping them and leaving them inline be sufficient?

**Comment by kemayo** [comment]
I'm thinking that I might change the current `--[skip|include]-spoilers` flag into `--spoilers=[footnote|inline|skip]`. (I guess technically I could do `endnote` as well, to put them at the end of the current-chapter.)

**Comment by KeinNiemand** [comment]
> The current experience works out okay for me because on a Kindle the footnotes are set up to trigger footnote-popups so I don't need to jump around.
> 
> That said, an option to "clean" them by leaving them inline seems reasonable -- do you think they need some sort of markup added to indicate which bits of the content were previously hidden-as-spoilers, or would just unwrapping them and leaving them inline be sufficient?

That all depends on the story sometimes just unwrapping it and putting it inline is enough other times you might need to know the spoilers title or that something was in a spoiler it all depends on what spoilers are used for so maybe make that an option as well.
For example sometimes in LITRPGs spoilers are used to hide status screens and things like that in that case inline would be enough but sometimes the spoilers name (on sites that can have named spoilers) is used to talk about witch characters status it's about so in that case you need the spoilers title.
