### ISSUE TITLE
Download only certain chapters - royal road

### ISSUE THREAD

**Issue by deepakramani** [kemayo/leech#88]
Hi,
Thanks for the script. I'm enjoying reading my favourite web novels in epub format.
I'd like to know whether it is possible to download only a bunch of chapters instead of a whole book. Something like chapter 50 onwards. I need this because as the novels get updated daily and have reached chapter 400, I'd like to download just the chapters after 400. Is it possible? If so how do I pass the arguments?

Example site - [https://www.royalroad.com/fiction/41618/mark-of-the-fool](https://www.royalroad.com/fiction/41618/mark-of-the-fool). 

Thanks.

**Comment by kemayo** [comment]
It's now possible as of 7230f65a689654d480c17426a9aa2fc34c752918. You just have to add the `--offset` option to the command. So e.g. `leech https://www.royalroad.com/fiction/41618/mark-of-the-fool --offset 400` would start downloading from chapter 401.

**Comment by deepakramani** [comment]
Thanks.
