### ISSUE TITLE
Don't add a space betweenn spans (Royalroad)

### ISSUE THREAD

**Issue by KeinNiemand** [kemayo/leech#92]
Leech seems to be adding spaces beween span tags which breaks Delve (https://www.royalroad.com/fiction/25225/delve' chapter 164 and probably others) since delve for some reason has the start of a word and the rest of the word in seperate tags. So Rain (MC) sometimes ends up as R ain, and other errors like that.

**Comment by kemayo** [comment]
Honestly, beautifulsoup doing this in a "prettify" operation is a pretty good argument for just removing all usage of `prettify` from the code. Such things really shouldn't semantically change the output.

An alternative might be to use something like @annedo's [prettierfier](https://github.com/annedo/prettierfier). But I think my main reason for prettifying when I added it back-in-the-day was to make debugging easier, so just removing it from the output entirely seems fair to start. 🤔
